dem:
  path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/dem_tile_0.tif'
  out_path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/dem' 


rgb:
  paths: ['/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/tile_10_0.tif', 
             '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/tile_12_0.tif', 
             '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/tile_14_0.tif',
             '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/tile_16_0.tif',
             '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/tile_18_0.tif',
             '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/tile_20_0.tif']
  out_path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Britt/rgb' 


