region:
  point_1: [39.260215,-92.190097] 
  point_2: [39.264652,-92.181670]
  point_3: [39.259367,-92.144871]
  point_4: [39.254430,-92.148810]


huc_number: &huc_number '15'

kmz_address: 
  extraction_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/SCs_to_download/SC_{huc_number}.kml'
  kmz_file_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/SCs_to_download/SC_{huc_number}.kml'



rgb:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/Google_Lines_Paper_Evaluation/downloaded_raw_{huc_number}/rgb/'
  spec:
    dimension: '2048x2048'
    format: "GEO_TIFF"
    prefix: ['tile_10_',
             'tile_12_',
             'tile_14_',
             'tile_16_',
             'tile_18_',
             'tile_20_']
    filter_dates: [['2010', '2012'],
                  ['2012', '2014'],
                  ['2014', '2016'],
                  ['2016', '2018'],
                  ['2018', '2020'],
                  ['2020', '2022']]

dem:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/Google_Lines_Paper_Evaluation/downloaded_raw_{huc_number}/dem'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'


merge:
  path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/Google_Lines_Paper_Evaluation/downloaded_raw_{huc_number}/merged'
  


