region:
  point_1: [-90.997728,39.126623]
  point_2: [-90.988519,39.122188]
  point_3: [-90.997851,39.117090]
  point_4: [-91.007803,39.120142]

rgb:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Ellis'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'tile_20_'
    filter_date_1: '2022'
    filter_date_2: '2020'

dem:
  choose: 0
  path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Ellis'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'
  


