region:
  point_1: [-90.997728,39.126623]
  point_2: [-90.988519,39.122188]
  point_3: [-90.997851,39.117090]
  point_4: [-91.007803,39.120142]



rgb:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/SO_Paper/data'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: ['tile_10_',
             'tile_12_',
             'tile_14_',
             'tile_16_',
             'tile_18_',
             'tile_20_']
    filter_dates: [['2010', '2012'],
                  ['2012', '2014'],
                  ['2014', '2016'],
                  ['2016', '2018'],
                  ['2018', '2020'],
                  ['2020', '2022']]

dem:
  choose: 0
  path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Ellis'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'
  


