region:
  point_1: [-91.636670,39.333897]
  point_2: [-91.632655,39.328732]
  point_3: [-91.638519,39.323193]
  point_4: [-91.644631,39.326990]



rgb:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Braunqardt'
  spec:
    dimension: '2048x2048'
    format: "GEO_TIFF"
    prefix: ['tile_10_',
             'tile_12_',
             'tile_14_',
             'tile_16_',
             'tile_18_',
             'tile_20_']
    filter_dates: [['2010', '2012'],
                  ['2012', '2014'],
                  ['2014', '2016'],
                  ['2016', '2018'],
                  ['2018', '2020'],
                  ['2020', '2022']]

dem:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/SO_Paper/data/Braunqardt'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'
  


