region:
  tif_file_path: '/home1/pupil/SMATousi/High_Res_Data/2023/Monroe/MonroeCountyHUC/5625_43583.tif'
  point_1: [40.465274,-94.680294] 
  point_2: [40.465837,-94.636896]
  point_3: [40.443150,-94.644243]
  point_4: [40.439484,-94.687236]


huc_number: &huc_number '15'

kmz_address: 
  extraction_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/highres/SC_{huc_number}.kml'
  kmz_file_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/highres/SC_{huc_number}.kml'



rgb:
  choose: 1
  path: '/home1/pupil/SMATousi/High_Res_Data/NAIP_from_GEE/Monroe/rgb/'
  spec:
    scale: 1.0
    dimension: '2048x2048'
    format: "GEO_TIFF"
    prefix: ['tile_10_',
             'tile_12_',
             'tile_14_',
             'tile_16_',
             'tile_18_',
             'tile_20_']
    filter_dates: [['2010', '2012'],
                  ['2012', '2014'],
                  ['2014', '2016'],
                  ['2016', '2018'],
                  ['2018', '2019'],
                  ['2020', '2022']]

# rgb:
#   choose: 1
#   path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/highres/downloaded_raw_{huc_number}/rgb/'
#   spec:
#     dimension: '2000x2000'
#     format: "GEO_TIFF"
#     prefix: [
#              'tile_14s_']
#     filter_dates: [
#                   ['2014', '2016']]



dem:
  choose: 0
  path: '/home1/pupil/SMATousi/High_Res_Data/NAIP_from_GEE/Monroe/dem'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'


merge:
  path: '/home1/pupil/SMATousi/High_Res_Data/NAIP_from_GEE/Monroe/merged'
  


