region:
  point_1: [-92.20260,39.28553] 
  point_2: [-92.05966,39.16790]
  point_3: [-92.22560,39.08444]
  point_4: [-92.31892,39.18498]


huc_number: &huc_number '102801011601'

kmz_address: 
  extraction_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/SCs_to_download/SC_{huc_number}.kml'
  kmz_file_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/SCs_to_download/SC_{huc_number}.kml'



rgb:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/Google_Lines_Paper_Evaluation/downloaded_raw/rgb/'
  spec:
    dimension: '2048x2048'
    format: "GEO_TIFF"
    prefix: ['tile_10_',
             'tile_12_',
             'tile_14_',
             'tile_16_',
             'tile_18_',
             'tile_20_']
    filter_dates: [['2010', '2012'],
                  ['2012', '2014'],
                  ['2014', '2016'],
                  ['2016', '2018'],
                  ['2018', '2020'],
                  ['2020', '2022']]

dem:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/Google_Lines_Paper_Evaluation/downloaded_raw/dem'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'


merge:
  path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/Google_Lines_Paper_Evaluation/downloaded_raw/merged'
  


