specs:
  from_tif: 1

region:
  tif_file_path: '/home/macula/SMATousi/projects/vigir_remote_sensing/ndvi_calculation/Ellis-Field/rasterized_total_soil_survey_ellis.tif'
  point_1: [-90.998080,39.127663] 
  point_2: [-91.013487,39.120954]
  point_3: [-90.996923,39.113592]
  point_4: [-90.981398,39.121043]


huc_number: &huc_number '15'

kmz_address: 
  extraction_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/highres/SC_{huc_number}.kml'
  kmz_file_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/highres/SC_{huc_number}.kml'



rgb:
  choose: 0
  path: ''
  spec:
    scale: 1.0
    dimension: '2048x2048'
    format: "GEO_TIFF"
    prefix: ['tile_10_',
             'tile_12_',
             'tile_14_',
             'tile_16_',
             'tile_18_',
             'tile_20_',
             'tile_22_']
    filter_dates: [['2010', '2012'],
                  ['2012', '2014'],
                  ['2014', '2016'],
                  ['2016', '2018'],
                  ['2018', '2020'],
                  ['2020', '2022'],
                  ['2022', '2024']]

# rgb:
#   choose: 1
#   path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/highres/downloaded_raw_{huc_number}/rgb/'
#   spec:
#     dimension: '2000x2000'
#     format: "GEO_TIFF"
#     prefix: [
#              'tile_14s_']
#     filter_dates: [
#                   ['2014', '2016']]



dem:
  choose: 1
  path: '/home/macula/SMATousi/Desktop/temp_dem/dem'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'
    scale: 1.0


merge:
  path: '/home/macula/SMATousi/Desktop/temp_dem/merged'
  

MSDIS:
  path_to_merge: '/home1/pupil/SMATousi/High_Res_Data/2023/Monroe/MonroeCountyHUC'

