region:
  point_1: [-92.25584,39.44133]
  point_2: [-92.14776,39.50539]
  point_3: [-92.04512,39.43684]
  point_4: [-92.13784,39.37915]



kmz_address: 
  extraction_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/HUCs/HUC_070801030408'
  kmz_file_path: '/home/macula/SMATousi/Gullies/ground_truth/organized_data/HUCs/HUC_070801030408/SC_070801030408'



rgb:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/ground_truth/google_api/training_process/gully_detection/raw_data/HUC_071100060307/RGB'
  spec:
    dimension: '2048x2048'
    format: "GEO_TIFF"
    prefix: ['tile_10_',
             'tile_12_',
             'tile_14_',
             'tile_16_',
             'tile_18_',
             'tile_20_']
    filter_dates: [['2010', '2012'],
                  ['2012', '2014'],
                  ['2014', '2016'],
                  ['2016', '2018'],
                  ['2018', '2020'],
                  ['2020', '2022']]

dem:
  choose: 1
  path: '/home/macula/SMATousi/Gullies/ground_truth/google_api/training_process/gully_detection/raw_data/HUC_071100060307/DEM'
  spec:
    dimension: '2000x2000'
    format: "GEO_TIFF"
    prefix: 'dem_tile_'
    filter_date_1: '2022'
    filter_date_2: '2000'


merge:
  path: '/home/macula/SMATousi/Gullies/ground_truth/google_api/training_process/gully_detection/raw_data/HUC_071100060307/merged'
  


